/*based on https://stackoverflow.com/questions/51692018/multiple-pages-in-vue-js-cli*/
module.exports = {
	pages:{
		'index': {
			entry: 'src/pages/Main/main.js', /*Script entry point*/
			template: 'public/index.html', /*Auto-generated by vue*/
			title: 'Main Search',
			chunks: ['chunk-vendors', 'chunk-common', 'index']
		},
		'details':{
			entry: 'src/pages/Details/main.js',
			template: 'public/index.html', /*Same for all pages*/
			title: 'Details',
			chunks: ['chunk-vendors', 'chunk-common', 'details']
		}
	},
	publicPath: process.env.NODE_ENV === 'production'
		? '/SimpleFishBase_Front/' : '/'
}